export const STATUS = {
  REQUEST_KO: { id: 0, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_KO' },
  REQUEST_INOK: { id: 1, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_INOK' },
  REQUEST_OK: { id: 2, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_OK' },
  REQUEST_VALIDATE_DOC: { id: 3, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_VALIDATE_DOC' },
  REQUEST_REVIEW_DOC: { id: 4, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_REVIEW_DOC' },
  REQUEST_APPROVED: { id: 5, value: 'HOME.CONTAINERS.FRACTIONATION_PROCESS.REQUEST_APPROVED' },
  REQUEST_FINISH: {id: 6, value: ''}
};
